import type { Metadata } from "next";
import "./globals.css"
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={``}
      >
           <div className="min-h-screen bg-background">
      {/* Header */}
      <header className="border-b border-border bg-card">
        <div className="container mx-auto px-4 py-6">
          <h1 className="text-3xl font-bold text-primary text-center tracking-wider">DJ SET STUDIO</h1>
          <p className="text-center text-muted-foreground mt-2">Professional Auto-Play Turntables</p>
        </div>
      </header>
        {children}
            {/* Status Bar */}
        <div className="mt-12 bg-card border border-border rounded-lg p-4">
          <div className="flex items-center justify-between text-sm">
            <div className="flex items-center space-x-4">
              <div className="flex items-center space-x-2">
                <div className="w-2 h-2 bg-primary rounded-full animate-pulse"></div>
                <span className="text-muted-foreground">AUTO-PLAY ACTIVE</span>
              </div>
              <div className="text-muted-foreground">|</div>
            </div>
            <div className="text-muted-foreground">Session Time: 00:00:00</div>
          </div>
        </div>
        </div>
      </body>
    </html>
  );
}
